In [1]:
#Export dependencies
import pandas as pd
import numpy as np

In [2]:
#Export data for cleaning
data = "Resources/Chicago_Energy_Benchmarking.csv"
chicago_energy_data = pd.read_csv(data)


chicago_energy_data.head()

,Data Year,ID,Property Name,Reporting Status,Address,ZIP Code,Chicago Energy Rating,Exempt From Chicago Energy Rating,Community Area,Primary Property Type,...,Site EUI (kBtu/sq ft),Source EUI (kBtu/sq ft),Weather Normalized Site EUI (kBtu/sq ft),Weather Normalized Source EUI (kBtu/sq ft),Total GHG Emissions (Metric Tons CO2e),GHG Intensity (kg CO2e/sq ft),Latitude,Longitude,Location,Row_ID
0,2020,252064,Mansueto Library,Submitted Data,1100 E 57th St,60637,2.0,False,HYDE PARK,Library,...,240.8,323.6,246.0,329.9,1160.9,18.1,41.792213,-87.599950,"(41.79221307, -87.59994981)",2020-252064
1,2020,232458,Harper Square Cooperative,Submitted Data,4800 - 4850 S Lake Park Ave,60615,1.0,False,KENWOOD,Multifamily Housing,...,95.5,146.0,100.3,150.7,4871.7,7.8,41.807475,-87.591264,"(41.80747487, -87.59126397)",2020-232458
2,2020,254616,Former Coyne College,Submitted Data,330 N Green St,60607,2.0,False,NEAR WEST SIDE,Office,...,55.5,148.3,56.7,151.8,4581.4,8.2,41.873335,-87.651021,"(41.873335, -87.65102071)",2020-254616
3,2020,103812,400 W Superior St,Submitted Data,400 W Superior St,60654,3.0,False,NEAR NORTH SIDE,Office,...,61.4,151.8,63.0,154.8,1092.1,8.4,41.895752,-87.638901,"(41.89575232, -87.638901)",2020-103812
4,2020,254073,Blue Moon Lofts,Submitted Data,215 N. Aberdeen St.,60607,4.0,False,NEAR WEST SIDE,Multifamily Housing,...,29.4,64.9,29.6,64.3,295.8,3.6,41.874295,-87.650175,"(41.87429514, -87.65017516)",2020-254073

# View imported data

In [3]:

chicago_energy_data = chicago_energy_data.set_index('ID')

In [4]:
#Check dimensions of data 
print(f'Number of columns: {chicago_energy_data.columns.nunique()}')
print(f'Number of rows: {len(chicago_energy_data)}')

Number of columns: 29
Number of rows: 17728

In [5]:
#Extracting exempt buildings
exempt_chicago_energy = chicago_energy_data.loc[(chicago_energy_data["Reporting Status"]) == 'Exempt']
print(len(exempt_chicago_energy))

474

In [6]:
nonexempt_chicago_energy = chicago_energy_data.loc[(chicago_energy_data["Reporting Status"]) != 'Exempt']
print(len(nonexempt_chicago_energy))

17254

In [7]:
#Dropping unnecessary columns
nonexempt_chicago_energy = nonexempt_chicago_energy.drop(columns='Row_ID')

# Check for null values

In [8]:
#Each row has an Chicago Energy Rating
null_val_energy_rating = (nonexempt_chicago_energy["Chicago Energy Rating"]).notnull()
null_val_energy_rating.describe

<bound method NDFrame.describe of ID
252064    True
232458    True
254616    True
103812    True
254073    True
          ...
260132    True
260135    True
260149    True
260150    True
260184    True
Name: Chicago Energy Rating, Length: 17254, dtype: bool>

In [9]:
nonexempt_chicago_energy.replace(r'^\s+$', np.nan, regex=True)

,Data Year,Property Name,Reporting Status,Address,ZIP Code,Chicago Energy Rating,Exempt From Chicago Energy Rating,Community Area,Primary Property Type,Gross Floor Area - Buildings (sq ft),...,All Other Fuel Use (kBtu),Site EUI (kBtu/sq ft),Source EUI (kBtu/sq ft),Weather Normalized Site EUI (kBtu/sq ft),Weather Normalized Source EUI (kBtu/sq ft),Total GHG Emissions (Metric Tons CO2e),GHG Intensity (kg CO2e/sq ft),Latitude,Longitude,Location
ID,,,,,,,,,,,,,,,,,,,,,
252064,2020,Mansueto Library,Submitted Data,1100 E 57th St,60637,2.0,False,HYDE PARK,Library,64028.0,...,NaN,240.8,323.6,246.0,329.9,1160.9,18.1,41.792213,-87.599950,"(41.79221307, -87.59994981)"
232458,2020,Harper Square Cooperative,Submitted Data,4800 - 4850 S Lake Park Ave,60615,1.0,False,KENWOOD,Multifamily Housing,627680.0,...,NaN,95.5,146.0,100.3,150.7,4871.7,7.8,41.807475,-87.591264,"(41.80747487, -87.59126397)"
254616,2020,Former Coyne College,Submitted Data,330 N Green St,60607,2.0,False,NEAR WEST SIDE,Office,555524.0,...,NaN,55.5,148.3,56.7,151.8,4581.4,8.2,41.873335,-87.651021,"(41.873335, -87.65102071)"
103812,2020,400 W Superior St,Submitted Data,400 W Superior St,60654,3.0,False,NEAR NORTH SIDE,Office,130007.0,...,NaN,61.4,151.8,63.0,154.8,1092.1,8.4,41.895752,-87.638901,"(41.89575232, -87.638901)"
254073,2020,Blue Moon Lofts,Submitted Data,215 N. Aberdeen St.,60607,4.0,False,NEAR WEST SIDE,Multifamily Housing,83000.0,...,NaN,29.4,64.9,29.6,64.3,295.8,3.6,41.874295,-87.650175,"(41.87429514, -87.65017516)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260132,2019,Q11970,Submitted,2401 W Grace St,60618,3.0,False,NORTH CENTER,NaN,NaN,...,NaN,72.5,165.6,71.7,NaN,NaN,NaN,41.950035,-87.688779,"(41.95003548, -87.68877942)"
260135,2019,309-315 W. 23rd St. Condominium Assocation,Submitted,309 W 23RD ST,60616,4.0,False,ARMOUR SQUARE,Multifamily Housing,52835.0,...,NaN,47.4,NaN,NaN,NaN,NaN,NaN,41.845504,-87.630557,"(41.84550365, -87.63055693)"
260149,2019,Riverside Square and River's Edge - Chicago,Submitted,3145 S Ashland Ave,60608,2.0,False,MCKINLEY PARK,Supermarket/Grocery Store,74495.0,...,NaN,254.7,566.2,253.4,NaN,2448.1,32.9,41.836579,-87.663845,"(41.8365795, -87.66384491)"
260150,2019,Cummings Life Science Center,Submitted,920 E 58th St,60637,2.0,False,HYDE PARK,Laboratory,172408.0,...,NaN,416.1,783.4,413.8,NaN,7815.5,45.3,41.789880,-87.602764,"(41.78987998, -87.60276375)"
260184,2019,Hampden Green Condominium Association,Submitted,2728 N HAMPDEN CT,60614,1.0,False,LINCOLN PARK,Multifamily Housing,140000.0,...,NaN,129.3,NaN,NaN,NaN,NaN,NaN,41.922011,-87.654620,"(41.92201051, -87.65461957)"

In [10]:
#Check replacement of blank rows with sample column
print(nonexempt_chicago_energy["All Other Fuel Use (kBtu)"].unique())

[           nan 7.65072000e+04 7.86470010e+06 1.03500000e+05
 1.65600000e+04 1.40760000e+05 4.02546000e+04 7.00902000e+04
 8.85546000e+04 2.44002000e+05 8.41800000e+04 5.91575000e+04
 1.79262000e+04 4.00200000e+04 8.02970000e+04 2.85660000e+04
 1.10623000e+04 7.55680000e+06 6.78960000e+04 2.20110000e+04
 8.43777000e+04 1.24200000e+04 2.27050000e+05 1.73880000e+05
 1.93296590e+06 1.50420000e+04 6.66678000e+05 3.32580000e+04
 2.09817950e+07 1.31320000e+04 5.36682000e+04 1.10400000e+04
 7.69210000e+04 1.03590000e+07 3.31200000e+04 3.14640000e+04
 6.79140000e+06 1.03222000e+05 4.48247000e+04 7.61760000e+04
 1.08054000e+05 1.94041800e+06 5.51448000e+05 8.91299840e+06
 5.63040000e+04 1.86300000e+04 6.97189990e+06 1.88090000e+04
 8.43120000e+04 4.41600000e+04 1.50470000e+04 1.42140000e+05
 4.92110000e+04 4.27800000e+04 8.54910000e+04 3.45000000e+03
 9.78930000e+04 1.94041790e+06 3.65700000e+04 1.58700000e+04
 6.60470000e+04 9.68200000e+06 5.64553000e+04 5.32211000e+04
 1.46560000e+04 3.15490000e+04 1.12080011e+07 1.04769600e+05
 7.06960000e+04 7.73352000e+04]

In [11]:
# of buildings by community
buildings_by_comm = nonexempt_chicago_energy["Community Area"].value_counts()
buildings_by_comm

NEAR NORTH SIDE                     2697
LOOP                                1960
NEAR WEST SIDE                      1264
LAKE VIEW                            908
LINCOLN PARK                         706
                                    ...
O'Hare                                 2
Lakeview                               1
West Lawn                              1
Pullman                                1
outside Chicago, in Bedford Park       1
Name: Community Area, Length: 130, dtype: int64

In [12]:
# electricity consumption by community
elec_consumption_by_comm = nonexempt_chicago_energy.groupby(["Community Area"]).sum()["Electricity Use (kBtu)"]
elec_consumption_by_comm

Community Area
ALBANY PARK                         2.087121e+08
ARCHER HEIGHTS                      2.880239e+08
ARMOUR SQUARE                       3.696204e+09
ASHBURN                             2.780577e+08
AUBURN GRESHAM                      1.727737e+08
                                        ...
West Pullman                        3.832139e+07
West Ridge                          1.115617e+07
West Town                           1.863136e+08
Woodlawn                            1.319849e+07
outside Chicago, in Bedford Park    6.597050e+06
Name: Electricity Use (kBtu), Length: 130, dtype: float64

In [13]:
gas_consumption_by_comm = nonexempt_chicago_energy.groupby(["Community Area"]).sum()["Natural Gas Use (kBtu)"]
gas_consumption_by_comm

Community Area
ALBANY PARK                         3.932679e+08
ARCHER HEIGHTS                      1.787444e+08
ARMOUR SQUARE                       3.124932e+09
ASHBURN                             4.011668e+08
AUBURN GRESHAM                      3.904656e+08
                                        ...
West Pullman                        6.363787e+07
West Ridge                          4.044531e+07
West Town                           2.155274e+08
Woodlawn                            1.822117e+07
outside Chicago, in Bedford Park    2.418400e+06
Name: Natural Gas Use (kBtu), Length: 130, dtype: float64

In [14]:
water_consumption_by_comm = nonexempt_chicago_energy.groupby(["Community Area"]).sum()["Water Use (kGal)"]
water_consumption_by_comm

Community Area
ALBANY PARK                          50775.0
ARCHER HEIGHTS                       20447.0
ARMOUR SQUARE                       163082.0
ASHBURN                              34077.0
AUBURN GRESHAM                       38496.0
                                      ...
West Pullman                          9682.0
West Ridge                            9808.0
West Town                            26607.0
Woodlawn                              1245.0
outside Chicago, in Bedford Park         0.0
Name: Water Use (kGal), Length: 130, dtype: float64

In [15]:
avg_energy_star_by_comm = nonexempt_chicago_energy.groupby(["Community Area"]).mean()["ENERGY STAR Score"]
avg_energy_star_by_comm

Community Area
ALBANY PARK                         62.984848
ARCHER HEIGHTS                      54.935484
ARMOUR SQUARE                       63.862069
ASHBURN                             54.943662
AUBURN GRESHAM                      41.105263
                                      ...
West Pullman                              NaN
West Ridge                          76.200000
West Town                           55.636364
Woodlawn                            60.800000
outside Chicago, in Bedford Park    70.000000
Name: ENERGY STAR Score, Length: 130, dtype: float64

In [16]:
#Change Column Names

In [24]:
import json
from geojson import Feature, FeatureCollection, Point

df = "Resources\Clean_data.csv"
df = pd.read_csv(df)

df.head()

,row_id,data_year,building_id,property_name,reporting_status,address,zip_code,chicago_energy_rating,exempt_from_chicago_energy_rating,community_area,...,natural_gas_use,site_eui,source_eui,weather_normalized_site_eui,weather_normalized_source_eui,total_ghg_emissions,ghg_intensity,lat,lon,loc
0,2020-252064,2020,252064,Mansueto Library,Submitted Data,1100 E 57th St,60637,2.0,False,HYDE PARK,...,0.0,240.8,323.6,246.0,329.9,1160.9,18.1,41.792213,-87.599950,"(41.79221307, -87.59994981)"
1,2020-232458,2020,232458,Harper Square Cooperative,Submitted Data,4800 - 4850 S Lake Park Ave,60615,1.0,False,KENWOOD,...,43537490.6,95.5,146.0,100.3,150.7,4871.7,7.8,41.807475,-87.591264,"(41.80747487, -87.59126397)"
2,2020-254616,2020,254616,Former Coyne College,Submitted Data,330 N Green St,60607,2.0,False,NEAR WEST SIDE,...,2199940.1,55.5,148.3,56.7,151.8,4581.4,8.2,41.873335,-87.651021,"(41.873335, -87.65102071)"
3,2020-103812,2020,103812,400 W Superior St,Submitted Data,400 W Superior St,60654,3.0,False,NEAR NORTH SIDE,...,1493523.2,61.4,151.8,63.0,154.8,1092.1,8.4,41.895752,-87.638901,"(41.89575232, -87.638901)"
4,2020-254073,2020,254073,Blue Moon Lofts,Submitted Data,215 N. Aberdeen St.,60607,4.0,False,NEAR WEST SIDE,...,825006.6,29.4,64.9,29.6,64.3,295.8,3.6,41.874295,-87.650175,"(41.87429514, -87.65017516)"

In [26]:
import json

# columns used for constructing geojson object
features = df.apply(
    lambda row: Feature(geometry=Point((float(row['lon']), float(row['lat'])))),
    axis=1).tolist()

# all the other columns used as properties
properties = df.drop(['lat', 'lon'], axis=1).to_dict('records')

# whole geojson object
feature_collection = FeatureCollection(features=features, properties=properties)

with open('testfile.geojson', 'w', encoding='utf-8') as f:
    json.dump(feature_collection, f, ensure_ascii=False)